# Generated by Django 3.2.9 on 2021-12-05 04:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=14)),
                ('authors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('number_of_pages', models.IntegerField()),
                ('publisher', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=25)),
                ('release_date', models.DateField()),
            ],
        ),
    ]
